[package]
name = "megaparse"
version = "0.1.0"
authors = ["jp <jpercyasnet@yahoo.com>"]
edition = "2021"
publish = false

[dependencies]
iced = "^0"
native-dialog = "^0"
iced_futures = "^0"
chrono = "^0"
#kamadak-exif = "^0"
#regex = "^0"
